#!/bin/bash
# Quick Start: Deploy to Production (Free Tier)

echo "🚀 Broadcasting Research Agent - Production Deployment"
echo ""
echo "This script prepares your project for production deployment on:"
echo "  • Frontend: Vercel (Free)"
echo "  • Backend: Render (Free)"
echo "  • LLM: Groq (Free)"
echo ""
echo "Prerequisites:"
echo "  ✓ Git repository initialized and pushed"
echo "  ✓ GitHub account"
echo "  ✓ Groq API key (get free at console.groq.com)"
echo ""

# Step 1: Verify git is clean
echo "📋 Step 1: Checking git status..."
if [ -n "$(git status --porcelain)" ]; then
    echo "❌ Git has uncommitted changes. Commit and push first:"
    echo "   git add ."
    echo "   git commit -m 'Production setup'"
    echo "   git push"
    exit 1
fi
echo "✅ Git is clean"

# Step 2: Get GitHub remote URL
echo ""
echo "📋 Step 2: Getting repository URL..."
REPO_URL=$(git config --get remote.origin.url)
echo "Repository: $REPO_URL"

# Step 3: Instructions
echo ""
echo "📋 Step 3: Deployment Instructions"
echo ""
echo "1️⃣  GROQ API KEY (5 minutes)"
echo "   • Go to: https://console.groq.com"
echo "   • Sign up (free)"
echo "   • Create API key"
echo "   • Keep this key ready"
echo ""

echo "2️⃣  DEPLOY BACKEND TO RENDER (10 minutes)"
echo "   • Go to: https://dashboard.render.com"
echo "   • Sign up with GitHub"
echo "   • Click 'New +' → 'Web Service'"
echo "   • Connect your repository: $REPO_URL"
echo "   • Configure:"
echo "     - Name: broadcaster-agent-backend"
echo "     - Runtime: Python 3.12"
echo "     - Build: pip install -r agents/python/requirements.txt"
echo "     - Start: python -m agents.python.inference_server"
echo "     - Instance: Free"
echo "   • Environment Variables:"
echo "     - GROQ_API_KEY: [paste your key]"
echo "     - AGENT_HOST: 0.0.0.0"
echo "     - AGENT_PORT: 8000"
echo "   • Click Deploy"
echo "   • ⏰ Wait 5-10 minutes"
echo "   • Copy your Render URL (e.g., https://broadcaster-agent-backend.onrender.com)"
echo ""

echo "3️⃣  DEPLOY FRONTEND TO VERCEL (5 minutes)"
echo "   • Go to: https://vercel.com"
echo "   • Click 'Add New' → 'Project'"
echo "   • Import your repository: $REPO_URL"
echo "   • Framework: Next.js (auto-detected)"
echo "   • Environment Variables:"
echo "     - NEXT_PUBLIC_API_URL: [your render URL from step 2]"
echo "     - NEXT_PUBLIC_COPILOTKIT_API_URL: [your render URL]/copilotkit"
echo "   • Click Deploy"
echo "   • ⏰ Wait 2-3 minutes"
echo "   • You'll get a Vercel URL"
echo ""

echo "4️⃣  TEST YOUR APP (10 minutes)"
echo "   • Go to your Vercel URL"
echo "   • Enter a broadcaster name"
echo "   • Open browser console (F12)"
echo "   • Try the research workflow"
echo "   • Watch logs in Render dashboard"
echo ""

echo "✅ DONE!"
echo ""
echo "URLs to bookmark:"
echo "  📱 Frontend: https://your-app.vercel.app"
echo "  🤖 Backend: https://broadcaster-agent-backend.onrender.com"
echo "  📊 Render Dashboard: https://dashboard.render.com"
echo "  📊 Vercel Dashboard: https://vercel.com/dashboard"
echo ""
echo "💰 Cost: $0/month (forever free tier)"
echo ""
echo "For full details, see: DEPLOYMENT.md"
