import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="/copilotkit.css" />
        <link rel="stylesheet" href="/copilotkit-overrides.css" />
      </head>
      <body suppressHydrationWarning>{children}</body>
    </html>
  )
}
